#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#                  Welcome to the Recap config, set your preferences here!
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
# Default Log example: (date - username: message)
# §cAUG 10 §7- §cZombiemold: §rThis is an example recap log!
#
# Formatting the time and date prefix of the log is done with Java 8's DateTimeFormatter class.
# The default is 'MMM dd' resulting in 'AUG 10' if the log is generated on August 10 (server time)
# Easy examples can be referenced here (6. Useful formatting patterns):
# https://howtodoinjava.com/java/date-time/java8-datetimeformatter-example/
date-format: "MMM dd"

# You can either override the recap log with the current list loaded in the plugin runtime, or
# append it as you go. Either way the result will be saved in the config folder as recap.txt.
append-log: true

# Append the recap log with the username of the person making the log
log-author: true

# Display the latest recap log on server join for all players with the recap.notify permission
show-on-join: true

# Display newly created recaps to all online players with the recap.notify permission
notify-live: true

# Translate color codes using '&' in the recap message
allow-colors: true

# How many entries should be listed when checking the last recap
max-size: 10

# Display recap log from first to last entry (newest at the top)
fifo-sorting: true